server:
  port: 8080

spring:
  datasource:
    #MYSQL IN DIGITAL OCEAN CLUSTER REMOTE
    #    url: ${MYSQL_USER_CLUSTER}
    #    username: ${MYSQL_USER_CLUSTER}
    #    password: ${MYSQL_PASSWORD_CLUSTER}

    #MYSQL IN LOCALHOST
    #    url: ${MYSQL_USER_LOCALHOST}
    #    username: ${MYSQL_USER_LOCALHOST}
    #    password: ${MYSQL_PASSWORD_LOCALHOST}

    #MYSQL IN DOCKER REMOTE
    #    url: ${MYSQL_URL_DOCKER_REMOTE}
    #    username: ${MYSQL_USER_DOCKER_REMOTE}
    #    password: ${MYSQL_PASSWORD_DOCKER_REMOTE}

    #MYSQL IN DOCKER LOCALHOST
    url: ${MYSQL_URL_DOCKER_LOCALHOST}
    username: ${MYSQL_USER_DOCKER_LOCALHOST}
    password: ${MYSQL_PASSWORD_DOCKER_LOCALHOST}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true